### ISSUE TITLE
(Response to Feedback Item 11) Drop SP-05

### ISSUE THREAD

**Issue by judielaine** [KantaraInitiative/SAMLprofiles#102]
See discussion 2018-07-12

**Comment by judielaine** [comment]
Erm, it seems @protag  completed this already.

**Comment by judielaine** [comment]
Wiki response: While including a <saml:Subject>  is not an appropriate method for managing step up authentication, we will refrain from stating a MUST NOT.

**Comment by scantor** [comment]
I would suggest s/appropriate/standardized, it's bit more politic.
