### ISSUE TITLE
(Response to feedback item 21) Clarify intent of "single child text node"

### ISSUE THREAD

**Issue by ergood** [KantaraInitiative/SAMLprofiles#108]
Profile states: “[SDP-IDP18] It is RECOMMENDED that the content of <saml:AttributeValue> elements be limited to a single child text node (i.e., a simple string value).”

Commenter responds: “That sounds like a "SHOULD NOT release multi-valued attributes (at least not properly multi-valued as SAML intends)". We certainly don't want to encourage people to violate our own specs (eduPerson's affiliation has a MUST requirement for also asserting member for certain other affiliation values) or to release multiple values as one concatenated string instead.”

This is not intended to preclude comma delimited values or multii-valued attributes. 

Scott to take a pass at clarifying the the text.

**Comment by scantor** [comment]
Added PR.
