### ISSUE TITLE
[SDP-IDP33]: shibmd:Scope in EntityDescriptor vs RoleDescriptor

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [KantaraInitiative/SAMLprofiles#135]
Hi,

Besides #134, I caught another similar issue: 
[SDP-IDP33] says:

> By virtue of this profile’s requirements, an IdP’s metadata MUST contain:
> * an <md:Extensions> element at the role level containing
>    * at least one <shibmd:Scope> element
>       * alternately, the <shibmd:Scope> element(s) MAY instead reside in an <md:Extensions> element at the root (<md:EntityDescriptor>) level

Because the first bullet-point quoted here (md:Extensions) sits at the 
same (top) level as the one about `md:IDPSSODescriptor`, it does not 
nest the Extensions into the role descriptor, and it instead reads as 
being at the top (EntityDescriptor) level.

However, the third-nested bullet-point ("Alternatively") assumes the 
*role* descriptor was meant by the text quoted above and says "or 
alternatively, can be at the top level".

Minor wording inconsistency - it should be clear what was meant about 
overall placing of `md:Extensions`  -  whether inside a Role descriptor or 
at the top level EntityDescriptor.

Cheers,
Vlad

**Comment by scantor** [comment]
Not sure I agree but I guess we could indent the bullets.

**Comment by scantor** [comment]
Fixed indentation.

**Comment by vladimir-mencl-eresearch** [comment]
And thanks for this clarification too - now it is clear where these extensions should go.
