### ISSUE TITLE
Combine SP/IdP metadata requirements?

### ISSUE THREAD

**Issue by scantor** [KantaraInitiative/SAMLprofiles#2]
Did we have a reason for having separate SP and IdP requirements for MDQ and Algorithm Extension support? If they're left as is, they look like identical requirements that belong up in the main metadata/trust section.

I'd defer until we settle on requirements for MDQ since that might fork differently for IdP and SP.

**Comment by wfhoehn** [comment]
> On Jul 27, 2016, at 5:42 PM, Scott Cantor <notifications@github.com> wrote:
> 
> Did we have a reason for having separate SP and IdP requirements for MDQ

“Identity Providers MUST,” whereas “Service Providers SHOULD.” That’s the only reason they are split.

> and Algorithm Extension support?

Sorry, what are you referring to? The requirement for “Metadata Extension for Algorithm Support” is under “Common Requirements.”

> If they're left as is, they look like identical requirements that belong up in the main metadata/trust section.
> 
> I'd defer until we settle on requirements for MDQ since that might fork differently for IdP and SP.

**Comment by scantor** [comment]
Ugh, I'm blind. Stared at that for 10 minutes and still missed it. Same issue applies with the algorithm issue. There are two requirements about that right after the MDQ ones.
