### ISSUE TITLE
Section 3.2.2 Metadata validation

### ISSUE THREAD

**Issue by ergood** [KantaraInitiative/SAMLprofiles#23]
no operational keys in metadata should be used to themselves establish trust in the metadata

**Comment by scantor** [comment]
I hesitated to apply this because it seemed to fit better at the end of 3.2.1. Wanted to make sure there wasn't a specific reason to put this in 3.2.2.

**Comment by ergood** [comment]
I can see it either way. No issue with it going into 3.2.1 instead.
