### ISSUE TITLE
Meta issue: Section numbering Deployment vs. Implementation profile

### ISSUE THREAD

**Issue by ergood** [KantaraInitiative/SAMLprofiles#25]
Do we want normative numbering that is related between the two?

**Comment by ergood** [comment]
Agreed that we will attempt to create a requirement numbering format that is consistent with the Implementation Profile, but not one that is "normatively related" to it. Implementation Profile labels are of the form [IIP-Type##] (e.g., [IIP-MD01] is the first Metadata requirement. We agreed to follow this practice, but not until the sections are mostly complete/static. Will need to select a prefix for saml2int requirements as well.

**Comment by ergood** [comment]
First pass at the numbering complete. Agreed to "SDP" (for SAML or SAML2int Deployment Profile) as the prefix for these requirements.

**Comment by alanbuxey** [comment]
assigned to Scott after pull request created

**Comment by alanbuxey** [comment]
believe this issue is closed
