### ISSUE TITLE
The `<saml2p:AuthnRequest>` message MUST NOT contain a `<saml2:Subject>` element.

### ISSUE THREAD

**Issue by judielaine** [KantaraInitiative/SAMLprofiles#32]
The `<saml2p:AuthnRequest>` message MUST NOT contain a `<saml2:Subject>` element.

2018-01-11 discussion:
* This is pretty common sense, and it’s not in our current version. Should it be? -KW’s email
* RECOMMEND PUT THIS BACK IN
* The general use case might have been in step up.
* But we are going to NameID is transient, so there.

**Comment by ergood** [comment]
Closing based on #35 and list discussion.
