### ISSUE TITLE
Reference review

### ISSUE THREAD

**Issue by scantor** [KantaraInitiative/SAMLprofiles#34]
We need to do a thorough review of the Reference sections to catch any incorrect links or links to the wrong versions of documents.

**Comment by nckroy** [comment]
Will leave this open per Scott Cantor until we can do a complete reference review.  Really hard to spot these things, want to keep this until we are done with other edits.

**Comment by nckroy** [comment]
See also #45

**Comment by alexstuart** [comment]
**SDP-SP28**: Text says "SPs SHOULD consider support for the SP Request Initiation Profile and Protocol defined in [IdPDisco]" but I think text should say "SPs SHOULD consider support for the Identity Provider Discovery Service Protocol and Profile defined in [IdPDisco]"

**Comment by scantor** [comment]
Good enough for government work.

**Comment by nckroy** [comment]
Closed per group discussion 3/29/2018
