### ISSUE TITLE
Last bullet point in Section 3.2.1 is "TBD?"

### ISSUE THREAD

**Issue by alexstuart** [KantaraInitiative/SAMLprofiles#43]
Examples should be given or the bullet point removed.

**Comment by ergood** [comment]
Multiple folks have reviewed the profile to see if anything is missing. Next step is for someone(s) to look at actual metadata to see if there are tags we failed to reference in the profile.

**Comment by alexstuart** [comment]
I've looked at all metadata in the UK federation aggregate (including what we import from eduGAIN) and cannot find any elements which are essential to technical interoperability that must be in metadata

**Comment by nckroy** [comment]
Closed per discussion 3/29/2018
