### ISSUE TITLE
Non-normative text in section 4.1.4 includes a question aimed at us profile writers

### ISSUE THREAD

**Issue by alexstuart** [KantaraInitiative/SAMLprofiles#44]
Text of section is

> When consuming SAML Attributes with standardized definitions in external specifications, SPs MUST NOT impose constraints beyond the definitions of those attributes.

> _This may imply supporting extra long attribute values, attributes that contain multiple values, broad character set support, etc. Maybe this is less critical with the subject ID changes?_

**Comment by scantor** [comment]
I think all those points are true, but are essentially the point here. If you consume, e.g. givenName, and tell somebody they have to send you one value, you are in error. That's what the language is trying to say. I will add that as an example, in fact.

**Comment by ergood** [comment]
For completeness, this was done in https://github.com/KantaraInitiative/SAMLprofiles/commit/47b359703aee17393261e9a9609499419a6d42fc#diff-23f56c777d3ee93fc4499ffb59fa8284
