### ISSUE TITLE
Two typos found

### ISSUE THREAD

**Issue by alexstuart** [KantaraInitiative/SAMLprofiles#45]
- In the introduction, "federation deployments involving thousands of Identity and SPs"

- in notation, the internal reference to SAML2ASLO is missing one `>`

**Comment by alexstuart** [comment]
I've addressed these typos in a commit in one of my GitHub repos (https://github.com/alexstuart/SAMLprofiles/commit/b8c3eac882bba451b4ccc5864b6c7c055d5d70ee) but I've screwed up my git branches so a pull request for that would be messy.

**Comment by nckroy** [comment]
Relates to #34

**Comment by alanbuxey** [comment]
i've submitted 2 pull requests

**Comment by nckroy** [comment]
close #45
