### ISSUE TITLE
3.2.2 exclusion

### ISSUE THREAD

**Issue by alanbuxey** [KantaraInitiative/SAMLprofiles#46]
"Deployments MUST NOT require out of band communication or coordination for the management of any behavior by peers included within the enumerated areas identified above."

would this negate any moves to use some form of additional data source or decoration of the provided metadata by another party - eg current WIP for Sirtfi ?

**Comment by scantor** [comment]
In addition to adding a bit of clarification, I suggest we move the relevant text from the production section to the consumption section, closer to the actual list of bulleted points.
