### ISSUE TITLE
cryptographic algorithms (3.3)

### ISSUE THREAD

**Issue by alanbuxey** [KantaraInitiative/SAMLprofiles#48]
do we want to align with NIST (and xmlsec tool) guidelines and blacklist the older sha-1 too?

Digest algorithm blacklist:
   http://www.w3.org/2000/09/xmldsig#sha1
   http://www.w3.org/2001/04/xmldsig-more#md5
Signature algorithm blacklist:
   http://www.w3.org/2000/09/xmldsig#rsa-sha1
   http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1
   http://www.w3.org/2001/04/xmldsig-more#rsa-md5

**Comment by scantor** [comment]
The test for me would be whether people are comfortable with the Shibboleth distributions blacklisting them by default or not.

**Comment by protag** [comment]
What algorithms are left to use if we blacklist these?  Would Shibboleth have a configuration that works with the majority of, say, InCommon relying parties?

**Comment by scantor** [comment]
The profile already specifies a set of default algorithms using SHA-256. Blacklisting SHA-1 probably doesn't impact very many people these days.
The requirement we already made for AES-GCM encryption and to blacklist CBC will be impossible for the majority of non-Shibboleth SPs, I would guess.
