### ISSUE TITLE
3.1.1. Clock Skew query

### ISSUE THREAD

**Issue by alanbuxey** [KantaraInitiative/SAMLprofiles#49]
"Deployments MUST allow for a minimum of three (3) and a maximum of five (5) minutes of clock skew — in either direction"

why a minimum? surely its okay for having a pretty much zero clock skew?

**Comment by scantor** [comment]
No, when we have problems it's because of zero skew, that doesn't work in an Internet scale system that also does timestamp checks. The minimum is crucial. The maximum is the one that's subject to opinion, the higher it is the looser the behavior.
