### ISSUE TITLE
SDP-MD09

### ISSUE THREAD

**Issue by judielaine** [KantaraInitiative/SAMLprofiles#81]
This is definitely an issue for interop in the general. It may be hidden in hub-spoke feds.

**Comment by scantor** [comment]
Removed confusing issue number conflict, this is issue 7 from the wiki table.

**Comment by scantor** [comment]
Moved over to Eric since he proposed a fix.

**Comment by ergood** [comment]
Adding references: 
This issue is a duplicate of #80, and is addressed by #87.
