### ISSUE TITLE
mdui:Logo SIZE clarification SDP-G02

### ISSUE THREAD

**Issue by judielaine** [KantaraInitiative/SAMLprofiles#86]
We should note that the size limitation (elsewhere) does not apply here

**Comment by alexstuart** [comment]
As we are [removing specifications of Logo size, format etc. in issue 77](https://github.com/KantaraInitiative/SAMLprofiles/issues/77), I don't think we need to explicitly include inline logo size in SDP-G02

**Comment by nckroy** [comment]
I agree with Alex

**Comment by nckroy** [comment]
Assigned to alex

**Comment by alexstuart** [comment]
https://github.com/KantaraInitiative/SAMLprofiles/issues/77 indicates that logos can be URLs or data URIs, so we must specify in SDP-MD12 that the data URI can exceed 256 characters (as required by SDP-SG02)

**Comment by alexstuart** [comment]
I've raised a pull request https://github.com/KantaraInitiative/SAMLprofiles/pull/104
