### ISSUE TITLE
Housekeeping on shibmd:scope

### ISSUE THREAD

**Issue by judielaine** [KantaraInitiative/SAMLprofiles#96]
clean up the shibboleth wiki doc on this topic to remove ‘under development’ and get the non-normative text added here that references the shibboleth docs.

 https://wiki.shibboleth.net/confluence/display/SC/ShibMetaExt+V1.0

**Comment by scantor** [comment]
The wiki side of this has been done, but this is superseded by a tentative decision to try to standardize this extension.
